version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=sqlite:///./agentic.db
    volumes:
      - ./backend:/app
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - agentic-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./backend/Modelfile:/models/Modelfile
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - agentic-network
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: serve && create agentic-specialist -f /models/Modelfile 
networks:
  agentic-network:
    driver: bridge

volumes:
  ollama-data:
